services:
  - type: web
    name: apple-calendar-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: ICLOUD_USERNAME
        sync: false
      - key: ICLOUD_APP_PASSWORD
        sync: false
